# Docker/supervisord.conf
[supervisord]
nodaemon=true
pidfile=/var/run/supervisord.pid
user=root
logfile=/dev/null

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/stderr       ; 將 nginx 的 stderr 導向容器的 stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/stderr       ; 將 php-fpm 的 stderr 導向容器的 stderr
stderr_logfile_maxbytes=0
